# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConfigboardCliEdge < Formula
  desc "configboard-cli"
  homepage "https://github.com/configboard/configboard-cli"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/configboard/configboard-cli/releases/download/v0.4.0/configboard-cli_v0.4.0_darwin_arm64.tar.gz"
      sha256 "96cd4ea3508a771cf73187f9bdc8ac370ff3888571d241615afda566f81aaa39"

      def install
        bin.install "configboard-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/configboard/configboard-cli/releases/download/v0.4.0/configboard-cli_v0.4.0_darwin_amd64.tar.gz"
      sha256 "4ca28a8db00756ca070d326edd4ff31459723e178d47ef1fed8a18560fbf57e4"

      def install
        bin.install "configboard-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/configboard/configboard-cli/releases/download/v0.4.0/configboard-cli_v0.4.0_linux_arm64.tar.gz"
      sha256 "3393559293bfb3207341779991a5a6d529bc71634bc4ecdd4d8bb0fa008dbe3d"

      def install
        bin.install "configboard-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/configboard/configboard-cli/releases/download/v0.4.0/configboard-cli_v0.4.0_linux_amd64.tar.gz"
      sha256 "64271bde82c38f94b59708c8d36f7aec53dc45f82429f0d08b2b17efcdb981e7"

      def install
        bin.install "configboard-cli"
      end
    end
  end

  conflicts_with "configboard-cli"

  def caveats; <<~EOS
    How to use this binary: https://github.com/configboard/configboard-cli
  EOS
  end

  test do
    system "#{bin}/configboard-cli version"
  end
end
