# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConfigboardCliEdge < Formula
  desc "configboard-cli"
  homepage "https://github.com/configboard/configboard-cli"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/configboard/configboard-cli/releases/download/v0.3.1/configboard-cli_v0.3.1_darwin_arm64.tar.gz"
      sha256 "07ee339ecdc7ef0f28d91b23a0cb16021195b62629620017a9f9631cf68bde18"

      def install
        bin.install "configboard-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/configboard/configboard-cli/releases/download/v0.3.1/configboard-cli_v0.3.1_darwin_amd64.tar.gz"
      sha256 "5396fbd6e1330659ebd532e90a231ca569f0693e094d3fd80f9d3f06340f6878"

      def install
        bin.install "configboard-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/configboard/configboard-cli/releases/download/v0.3.1/configboard-cli_v0.3.1_linux_arm64.tar.gz"
      sha256 "738ac4e86190d86a6c2be653ae9648d213b8e779af51af749fdf58ccaeea8a01"

      def install
        bin.install "configboard-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/configboard/configboard-cli/releases/download/v0.3.1/configboard-cli_v0.3.1_linux_amd64.tar.gz"
      sha256 "13d7edddb107b63b0d733a5716832632ceaeaa15285f84ce6b1d368cdacc813a"

      def install
        bin.install "configboard-cli"
      end
    end
  end

  conflicts_with "configboard-cli"

  def caveats; <<~EOS
    How to use this binary: https://github.com/configboard/configboard-cli
  EOS
  end

  test do
    system "#{bin}/configboard-cli version"
  end
end
