# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConfigboardCli < Formula
  desc "configboard-cli"
  homepage "https://github.com/configboard/configboard-cli"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/configboard/configboard-cli/releases/download/v0.2.0/configboard-cli_v0.2.0_darwin_arm64.tar.gz"
      sha256 "53c83913746610d23df0c2c7bb28a5383111fa2625c79d782f0f6263895623fd"

      def install
        bin.install "configboard-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/configboard/configboard-cli/releases/download/v0.2.0/configboard-cli_v0.2.0_darwin_amd64.tar.gz"
      sha256 "5f0e21ff5cdc57cf27f7c55e916ea7b91b6c1f97b4d2104b4f7967f0b818e1b7"

      def install
        bin.install "configboard-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/configboard/configboard-cli/releases/download/v0.2.0/configboard-cli_v0.2.0_linux_arm64.tar.gz"
      sha256 "d6ab5efd224bb22150e56ef0d4a6ec634fb778cbac8f0fdcae5a2cc2b4e75ac0"

      def install
        bin.install "configboard-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/configboard/configboard-cli/releases/download/v0.2.0/configboard-cli_v0.2.0_linux_amd64.tar.gz"
      sha256 "a747c99aa3c0fc03c9326985b3ec348035f16b4c6a4243d0090c9220ac4a9f29"

      def install
        bin.install "configboard-cli"
      end
    end
  end

  conflicts_with "configboard-cli-edge"

  def caveats; <<~EOS
    How to use this binary: https://github.com/configboard/configboard-cli
  EOS
  end

  test do
    system "#{bin}/configboard-cli version"
  end
end
