# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConfigboardServerPocEdge < Formula
  desc "configboard-server-poc"
  homepage "https://github.com/configboard/configboard-server-poc"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/configboard/configboard-server-poc/releases/download/v0.1.0/configboard-server-poc_v0.1.0_darwin_arm64.tar.gz"
      sha256 "99e053230af088d4b5647139eadfde369dc23ff160a3170c6ac58221efdc82f4"

      def install
        bin.install "configboard-server-poc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/configboard/configboard-server-poc/releases/download/v0.1.0/configboard-server-poc_v0.1.0_darwin_amd64.tar.gz"
      sha256 "76b0dd4af08390e52e06b919c5dac85a2fa82b57b7f67d606a7399c7fa3e921e"

      def install
        bin.install "configboard-server-poc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/configboard/configboard-server-poc/releases/download/v0.1.0/configboard-server-poc_v0.1.0_linux_arm64.tar.gz"
      sha256 "a27bf01242ae7a8efdf7218abb5f7df9279e5d5223ab108e0ee135960260d23e"

      def install
        bin.install "configboard-server-poc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/configboard/configboard-server-poc/releases/download/v0.1.0/configboard-server-poc_v0.1.0_linux_amd64.tar.gz"
      sha256 "cf721e079788485fd3c478d46acc01c57bcb576837d24663e3af74054b934fda"

      def install
        bin.install "configboard-server-poc"
      end
    end
  end

  conflicts_with "configboard-server-poc"

  def caveats; <<~EOS
    How to use this binary: https://github.com/configboard/configboard-server-poc
  EOS
  end

  test do
    system "#{bin}/configboard-server-poc version"
  end
end
