# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConfigboardServerPoc < Formula
  desc "configboard-server-poc"
  homepage "https://github.com/configboard/configboard-server-poc"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/configboard/configboard-server-poc/releases/download/v0.3.0/configboard-server-poc_v0.3.0_darwin_arm64.tar.gz"
      sha256 "4594b9604733fecab973913470386390f943515f9b948f4b13f547bd372090d2"

      def install
        bin.install "configboard-server-poc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/configboard/configboard-server-poc/releases/download/v0.3.0/configboard-server-poc_v0.3.0_darwin_amd64.tar.gz"
      sha256 "23de2b5e37f4845f2562432e3eac1d5bbf40ae0e8848f650c0ac968af3a65c54"

      def install
        bin.install "configboard-server-poc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/configboard/configboard-server-poc/releases/download/v0.3.0/configboard-server-poc_v0.3.0_linux_arm64.tar.gz"
      sha256 "2ab31cc8651907ce07489b403b0aaeaaacf1fbaa4a09ac8751ae160755adac77"

      def install
        bin.install "configboard-server-poc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/configboard/configboard-server-poc/releases/download/v0.3.0/configboard-server-poc_v0.3.0_linux_amd64.tar.gz"
      sha256 "f8a636252bbf5648ce772e313225c3c6ff14c0d1fd89a75d30be15387b07cdb4"

      def install
        bin.install "configboard-server-poc"
      end
    end
  end

  conflicts_with "configboard-server-poc-edge"

  def caveats; <<~EOS
    How to use this binary: https://github.com/configboard/configboard-server-poc
  EOS
  end

  test do
    system "#{bin}/configboard-server-poc version"
  end
end
