# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConfigboardServerPoc < Formula
  desc "configboard-server-poc"
  homepage "https://github.com/configboard/configboard-server-poc"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/configboard/configboard-server-poc/releases/download/v0.2.0/configboard-server-poc_v0.2.0_darwin_arm64.tar.gz"
      sha256 "773fd2ed473b4dd76960190ea788e824b725e60a7e063e03d384d1e40056cd54"

      def install
        bin.install "configboard-server-poc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/configboard/configboard-server-poc/releases/download/v0.2.0/configboard-server-poc_v0.2.0_darwin_amd64.tar.gz"
      sha256 "243633fd5b3f9f8e4b13a65e6c4866f06bb53724add0ee9693cc227985af9de5"

      def install
        bin.install "configboard-server-poc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/configboard/configboard-server-poc/releases/download/v0.2.0/configboard-server-poc_v0.2.0_linux_arm64.tar.gz"
      sha256 "18619e3e5a62a4b7ed1563a52c95b648bfbf0287b9d480dea29ed960182c20e4"

      def install
        bin.install "configboard-server-poc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/configboard/configboard-server-poc/releases/download/v0.2.0/configboard-server-poc_v0.2.0_linux_amd64.tar.gz"
      sha256 "6af8957a01fdbae8bac2b9c23687f30961521a76f6a057989d5370f92c37b8ee"

      def install
        bin.install "configboard-server-poc"
      end
    end
  end

  conflicts_with "configboard-server-poc-edge"

  def caveats; <<~EOS
    How to use this binary: https://github.com/configboard/configboard-server-poc
  EOS
  end

  test do
    system "#{bin}/configboard-server-poc version"
  end
end
